version: "3.8"

services:
  web:
    build: .
    container_name: clinic_web
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_USER=clinic_user
      - MYSQL_PASSWORD=pass
      - MYSQL_DATABASE=clinic
    networks:
      - clinic_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 5

  db:
    image: mysql:8.0
    container_name: clinic_db
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: clinic
      MYSQL_USER: clinic_user
      MYSQL_PASSWORD: pass
    volumes:
      - db_data:/var/lib/mysql
      - ./db.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - clinic_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: clinic_phpmyadmin
    depends_on:
      - db
    ports:
      - "8081:80"
    environment:
      - PMA_HOST=db
      - MYSQL_ROOT_PASSWORD=pass
    networks:
      - clinic_network

volumes:
  db_data:

networks:
  clinic_network:
    driver: bridge


