version: "3.8"

services:
  web:
    build: .
    container_name: clinic_web
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: clinic_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: clinic
      MYSQL_USER: root
      MYSQL_PASSWORD: ""
    volumes:
      - ./clinic_database:/var/lib/mysql
      - ./db.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data:
